config/routes.rb
PoolUp::Application.routes.draw do
  resources :stops, only: :index
  resources :vehicles
  resources :driver_journeys
  resources :passenger_journeys
  resources :journeys
  resources :journey_bookings, only: [:create, :destroy] do
    put :confirm
  end
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get "home/index"
  devise_for :users
  resources :users

  root 'home#index'

end

app/models/journeys/passenger_journey.rb
class PassengerJourney < Journey

  has_many :journey_bookings, foreign_key: :passenger_journey_id

  has_many :driver_journeys, through: :journey_bookings

end

app/controllers/passenger_journeys_controller.rb
class PassengerJourneysController < ApplicationController
  before_action :set_passenger_journey, only: [:show, :edit, :update, :destroy]

  # GET /passenger_journeys
  # GET /passenger_journeys.json
  def index
    @driver_journey = DriverJourney.find(params[:journey_id])
    @passenger_journeys = Passenger.new(@driver_journey, params).passenger_journeys
    respond_to do |format|
      format.html { render action: 'index' }
      format.js { render action: 'index' }
      format.json { render json: @passenger_journeys }
    end
  end

  # GET /passenger_journeys/1
  # GET /passenger_journeys/1.json
  def show
    @driver_journeys = Driver.new(@passenger_journey).driver_journeys
  end

  # GET /passenger_journeys/new
  def new
    @passenger_journey = PassengerJourney.new
  end

  # GET /passenger_journeys/1/edit
  def edit
  end

  # POST /passenger_journeys
  # POST /passenger_journeys.json
  def create
    @passenger_journey = PassengerJourney.new(passenger_journey_params)

    respond_to do |format|
      if @passenger_journey.save
        format.html { redirect_to journeys_url, notice: 'Passenger journey was successfully created.' }
        format.json { render action: 'show', status: :created, location: @passenger_journey }
      else
        format.html { render action: 'new' }
        format.json { render json: @passenger_journey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passenger_journeys/1
  # PATCH/PUT /passenger_journeys/1.json
  def update
    respond_to do |format|
      if @passenger_journey.update(passenger_journey_params)
        format.html { redirect_to journeys_url, notice: 'Passenger journey was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @passenger_journey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passenger_journeys/1
  # DELETE /passenger_journeys/1.json
  def destroy
    @passenger_journey.destroy
    respond_to do |format|
      format.html { redirect_to journeys_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passenger_journey
      @passenger_journey = PassengerJourney.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def passenger_journey_params
      params[:passenger_journey].permit(:source_id, :destination_id, :user_id, :start_time, :end_time)
    end
end

app/views/passenger_journeys/_driver_journey.html.slim
- @driver_journeys.each do |journey|
  .large-6.small-12.columns.list_section
    .panel.radius
      .row
        .large-12.small-12.columns
          .large-9.small-12.columns
            = "#{journey.user.full_name}"
            br
            br
            = "#{journey.source.name} to #{journey.destination.name} (#{journey.start_time} to #{journey.end_time})"
          .large-3.small-12.columns
            = link_to 'Add', journey_bookings_path(journey_booking: { driver_journey_id: journey.id, passenger_journey_id: @passenger_journey.id}), class: 'secondary button small add_driver'

app/views/passenger_journeys/_form.html.slim
= simple_form_for(@passenger_journey) do |f|
  = f.error_notification

  .form-inputs
    = f.input :source_id
    = f.input :start_time
    = f.input :destination_id
    = f.input :end_time
    = f.hidden_field :user_id, value: current_user.id 
  
  .form-actions
    = f.button :submit, class: "secondary medium"
    | &nbsp;
    = link_to 'Back', driver_journeys_path, class: "button medium alert"

app/views/passenger_journeys/edit.html.slim
.large-8.columns
  h2
    | Editing passenger_journey

  == render 'form'

  = link_to 'Show', @passenger_journey, class: "button primary medium"

app/views/passenger_journeys/index.html.slim
h1 Listing passenger_journeys

table
  tr
    th
    th
    th

  - @passenger_journeys.each do |passenger_journey|
    tr
      td = link_to 'Show', passenger_journey
      td = link_to 'Edit', edit_passenger_journey_path(passenger_journey)
      td = link_to 'Destroy', passenger_journey, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Passenger journey', new_passenger_journey_path

app/views/passenger_journeys/index.js.erb
$('.list_for_adding_journey').html(<%= escape_javascript render 'driver_journeys/passenger_journey' %>);

app/views/passenger_journeys/new.html.slim
.large-8.columns
  h2
    | New passenger_journey

  == render 'form'

app/views/passenger_journeys/show.html.slim
.row
  .large-12.columns
    br
    h3
      = "#{@passenger_journey.source.name} to #{@passenger_journey.destination.name} (#{@passenger_journey.start_time} to #{@passenger_journey.end_time})"
    
    = link_to 'Edit', edit_passenger_journey_path(@passenger_journey)
    '|
    = link_to 'Back', journeys_path
  br
  br
  h4
    | Selected Drivers
  br
  .row
    .large-12.columns.selected_journey
      - @passenger_journey.driver_journeys.each do |journey|
        .large-6.small-12.columns.list_section
          .panel.radius
            .row
              .large-12.small-12.columns
                .large-9.small-12.columns
                  = "#{journey.user.full_name}"
                  br
                  br
                  = "#{journey.source.name} to #{journey.destination.name} (#{journey.start_time} to #{journey.end_time})" 

  .row
    .large-12.columns
      br
      h4 Check for other Places by adding to filter
      = form_tag(driver_journeys_path, method: "get", class: :custom, remote: true) do
        .large-6.columns
          label Start Point
          = text_field_tag 'start_point'
        .large-6.columns
          label End Point
          = text_field_tag 'end_point'
        .large-12.columns
          = hidden_field_tag 'journey_id', @passenger_journey.id
        .large-12.columns
          = submit_tag 'Go'
  br
  br
  .row
    .large-12.columns.list_for_adding_journey
      = render 'driver_journey'