config/routes.rb
PoolUp::Application.routes.draw do
  resources :stops, only: :index
  resources :vehicles
  resources :driver_journeys
  resources :passenger_journeys
  resources :journeys
  resources :journey_bookings, only: [:create, :destroy] do
    put :confirm
  end
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get "home/index"
  devise_for :users
  resources :users

  root 'home#index'

end

app/models/journeys/driver_journey.rb
class DriverJourney < Journey

  validates :vehicle_id, presence: true

  has_many :journey_bookings, foreign_key: :driver_journey_id
  
  has_many :passenger_journeys, through: :journey_bookings

end

app/controllers/driver_journeys_controller.rb
class DriverJourneysController < ApplicationController
  before_action :set_driver_journey, only: [:show, :edit, :update, :destroy]

  # GET /driver_journeys
  # GET /driver_journeys.json
  def index
    @passenger_journey = PassengerJourney.find(params[:journey_id])
    @driver_journeys = Driver.new(@passenger_journey, params).driver_journeys
    respond_to do |format|
      format.html { render action: 'index' }
      format.js { render action: 'index' }
      format.json { render json: @driver_journeys }
    end
  end

  # GET /driver_journeys/1
  # GET /driver_journeys/1.json
  def show
    @passenger_journeys = Passenger.new(@driver_journey).passenger_journeys
  end

  # GET /driver_journeys/new
  def new
    @driver_journey = DriverJourney.new
    3.times do |i|
      @driver_journey.start_journey_stops.build(stop_type: 'start')
      @driver_journey.end_journey_stops.build(stop_type: 'end')
    end
  end

  # GET /driver_journeys/1/edit
  def edit
  end

  # POST /driver_journeys
  # POST /driver_journeys.json
  def create
    @driver_journey = DriverJourney.new(driver_journey_params)

    respond_to do |format|
      if @driver_journey.save
        format.html { redirect_to journeys_path, notice: 'Driver journey was successfully created.' }
        format.json { render action: 'show', status: :created, location: @driver_journey }
      else
        format.html { render action: 'new' }
        format.json { render json: @driver_journey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /driver_journeys/1
  # PATCH/PUT /driver_journeys/1.json
  def update
    respond_to do |format|
      if @driver_journey.update(driver_journey_params)
        format.html { redirect_to journeys_path, notice: 'Driver journey was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @driver_journey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /driver_journeys/1
  # DELETE /driver_journeys/1.json
  def destroy
    @driver_journey.destroy
    respond_to do |format|
      format.html { redirect_to journeys_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver_journey
      @driver_journey = DriverJourney.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def driver_journey_params
      params[:driver_journey].permit(
        :source_id,
        :destination_id,
        :user_id,
        :vehicle_id,
        :start_time,
        :end_time, 
        :journey_stops_attributes => [
          :stop_id,
          :stop_type
        ]
      )
    end
end

app/views/driver_journeys/_form.html.slim
= simple_form_for(@driver_journey) do |f|
  = f.error_notification

  .form-inputs
    = f.input :source_id
    = f.input :start_time
    = f.input :destination_id
    = f.input :end_time
    = f.input :vehicle_id, collection: current_user.vehicles
    = f.hidden_field :user_id, value: current_user.id
    p Start Points 
    = f.simple_fields_for :journey_stops, @driver_journey.start_journey_stops do |p|
      = p.input :stop_id, label: false
      = p.hidden_field :stop_type, value: 'start'
      = p.hidden_field :journey_id, value: @driver_journey.id
    p End Points
    = f.simple_fields_for :journey_stops, @driver_journey.end_journey_stops do |p|
      = p.input :stop_id, label: false
      = p.hidden_field :stop_type, value: 'end'
      = p.hidden_field :journey_id, value: @driver_journey.id
  
  .form-actions
    = f.button :submit, class: "secondary medium"
    | &nbsp;
    = link_to 'Back', driver_journeys_path, class: "button medium alert"

app/views/driver_journeys/_passenger_journey.html.slim
- @passenger_journeys.each do |journey|
  .large-6.small-12.columns.list_section
    .panel.radius
      .row
        .large-12.small-12.columns
          .large-9.small-12.columns
            = "#{journey.user.full_name}"
            br
            br
            = "#{journey.source.name} to #{journey.destination.name} (#{journey.start_time} to #{journey.end_time})"
          .large-3.small-12.columns
            = link_to 'Add', journey_bookings_path(journey_booking: { driver_journey_id: @driver_journey.id, passenger_journey_id: journey.id}, driver_add: true), class: 'secondary button small add_passenger'

app/views/driver_journeys/edit.html.slim
.large-8.columns
  h2
    | Editing driver_journey

  == render 'form'

  = link_to 'Show', @driver_journey, class: "button medium primary"
  '|
  = link_to 'Back', driver_journeys_path, class: "button medium alert"

app/views/driver_journeys/index.html.slim
h1 Listing driver_journeys

table
  tr
    th
    th
    th

  - @driver_journeys.each do |driver_journey|
    tr
      td = link_to 'Show', driver_journey
      td = link_to 'Edit', edit_driver_journey_path(driver_journey)
      td = link_to 'Destroy', driver_journey, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Driver journey', new_driver_journey_path

app/views/driver_journeys/index.js.erb
$('.list_for_adding_journey').html(<%= escape_javascript render 'passenger_journeys/driver_journey' %>);

app/views/driver_journeys/new.html.slim
.large-8.columns
  h2
    | New driver_journey

  == render 'form'

  

app/views/driver_journeys/show.html.slim
.row
  .large-12.columns
    br
    h3
      = "#{@driver_journey.source.name} to #{@driver_journey.destination.name} (#{@driver_journey.start_time} to #{@driver_journey.end_time})"
    | Vacancies
    .total_vacancy
      = "#{@driver_journey.vehicle.vacancy}"
    
    = link_to 'Edit', edit_driver_journey_path(@driver_journey)
    '|
    = link_to 'Back', journeys_path

  br
  br
  h4
    | Selected Passengers
  br
  .row
    .large-12.columns.selected_journey
      - @driver_journey.passenger_journeys.each do |journey|
        .large-6.small-12.columns.list_section
          .panel.radius
            .row
              .large-12.small-12.columns
                .large-9.small-12.columns
                  = "#{journey.user.full_name}"
                  br
                  br
                  = "#{journey.source.name} to #{journey.destination.name} (#{journey.start_time} to #{journey.end_time})" 

  .row
    .large-12.columns
      br
      h4 Check for other Places by adding to filter
      = form_tag(passenger_journeys_path, method: "get", class: :custom, remote: true) do
        .large-6.columns
          label Start Point
          = text_field_tag 'start_point'
        .large-6.columns
          label End Point
          = text_field_tag 'end_point'
        .large-12.columns
          = hidden_field_tag 'journey_id', @driver_journey.id
        .large-12.columns
          = submit_tag 'Go'
  br
  br
  .row
    .large-12.columns.list_for_adding_journey
      = render 'passenger_journey'