config/routes.rb
PoolUp::Application.routes.draw do
  resources :stops, only: :index
  resources :vehicles
  resources :driver_journeys
  resources :passenger_journeys
  resources :journeys
  resources :journey_bookings, only: [:create, :destroy] do
    put :confirm
  end
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get "home/index"
  devise_for :users
  resources :users

  root 'home#index'

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base

  validates :drive_type, :capacity, :plate_no, :model, :user_id, presence: true

  def name
    model
  end

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully created.' }
        format.json { render action: 'show', status: :created, location: @vehicle }
      else
        format.html { render action: 'new' }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params[:vehicle].permit(:drive_type, :capacity, :vacancy, :plate_no, :model, :user_id)
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.slim
= simple_form_for(@vehicle) do |f|
  = f.error_notification

  .form-inputs
  	= f.input :drive_type, collection: ['4-wheeler', '3-wheeler', '2-wheeler']
    = f.input :capacity
    = f.input :vacancy
    = f.input :plate_no
    = f.input :model
    = f.hidden_field :user_id, value: current_user.id 
  .form-actions
    = f.button :submit, class: "secondary small"

app/views/vehicles/edit.html.slim
.row
  .large-5.push-4.columns
		h2
		  | Editing vehicle

		== render 'form'

		= link_to 'Show', @vehicle
		'|
		= link_to 'Back', vehicles_path

app/views/vehicles/index.html.slim
h1 Listing vehicles

table
  tr
    th Drive type
    th Capacity
    th Vacancy
    th Plate No
    th Model
    th
    th
    th
    
  - @vehicles.each do |vehicle|
    tr
      td = vehicle.drive_type
      td = vehicle.capacity
      td = vehicle.vacancy
      td = vehicle.plate_no
      td = vehicle.model
    
      td = link_to 'Show', vehicle
      td = link_to 'Edit', edit_vehicle_path(vehicle)
      td = link_to 'Destroy', vehicle, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Vehicle', new_vehicle_path

app/views/vehicles/new.html.slim
.row
  .large-5.push-4.columns
		h2
		  | New vehicle

		== render 'form'

		= link_to 'Back', vehicles_path

app/views/vehicles/show.html.slim
p#notice = notice


= link_to 'Edit', edit_vehicle_path(@vehicle)
'|
= link_to 'Back', vehicles_path