config/routes.rb
PoolUp::Application.routes.draw do
  resources :stops, only: :index
  resources :vehicles
  resources :driver_journeys
  resources :passenger_journeys
  resources :journeys
  resources :journey_bookings, only: [:create, :destroy] do
    put :confirm
  end
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get "home/index"
  devise_for :users
  resources :users

  root 'home#index'

end

app/models/journey.rb
class Journey < ActiveRecord::Base

  belongs_to :source, class_name: "Stop" 
  belongs_to :destination, class_name: "Stop"
  belongs_to :user
  belongs_to :vehicle

  validates :source_id, :destination_id, :user_id, :start_time, :end_time, presence: true

  has_many :journey_stops
  has_many :stops, through: :journey_stops
  accepts_nested_attributes_for :journey_stops

  has_many :start_journey_stops, -> { where stop_type: 'start' }, class_name: 'JourneyStop'
  has_many :end_journey_stops, -> { where stop_type: 'end' }, class_name: 'JourneyStop'

end

app/models/journeys/driver_journey.rb
class DriverJourney < Journey

  validates :vehicle_id, presence: true

  has_many :journey_bookings, foreign_key: :driver_journey_id
  
  has_many :passenger_journeys, through: :journey_bookings

end

app/models/journeys/passenger_journey.rb
class PassengerJourney < Journey

  has_many :journey_bookings, foreign_key: :passenger_journey_id

  has_many :driver_journeys, through: :journey_bookings

end

app/controllers/journeys_controller.rb
class JourneysController < ApplicationController
  def index
  end
end

app/helpers/journeys_helper.rb
module JourneysHelper
end

app/views/journeys/index.html.slim
.row
  .large-12.columns
    h2
      | Your Carpool's
    br
    .row
      .large-12.columns
        h3
          | As A Driver
      - current_user.driver_journeys.each do |journey|
        .large-12.columns
          .panel.radius
            .row
              .large-12.small-12.columns
                h5
                  = "#{journey.source.name} to #{journey.destination.name} (#{journey.start_time} to #{journey.end_time})"
                hr
                .row
                  .large-6.small-12.columns
                    h6.subheader
                      | Vehicle Details
                      = "#{journey.vehicle.model} - #{journey.vehicle.plate_no} - #{journey.vehicle.vacancy} vacancies"
                      br
                      br
                      | Passenger Details :-
                      br
                      - if journey.journey_bookings.any?
                        = "#{journey.journey_bookings.count} passengers are added."
                      - else
                        = "No Passengers added yet"
                  .large-6.small-12.columns
                    h6.subheader
                      = link_to 'Add Passengers', driver_journey_path(journey), class: 'secondary button small'

    - if current_user.vehicles.any?
      = link_to 'As Driver', new_driver_journey_path, class: 'secondary button medium'
    - else
      = link_to 'As Driver', '#', class: 'secondary button medium disabled'
      = " Click "
      = link_to 'here', new_vehicle_path
      = " to share your ride."
    br
    br
    .row
      .large-12.columns
        h3
          | As A Passenger
      - current_user.passenger_journeys.each do |journey|
        .large-12.columns
          .panel.radius
            .row
              .large-12.small-12.columns
                h5
                  = "#{journey.source.name} to #{journey.destination.name} (#{journey.start_time} to #{journey.end_time})"
                hr
                .row
                  .large-6.small-12.columns
                    h6.subheader
                      | Drive Details :-
                      br
                      - if journey.journey_bookings.any?
                        = "Driver is added"
                      - else
                        = "Driver not added yet"
                  .large-6.small-12.columns
                    h6.subheader
                      = link_to 'Add Drivers', passenger_journey_path(journey), class: 'secondary button small' 
        
    = link_to 'As Passenger', new_passenger_journey_path, class: 'secondary button medium'
    
    